import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  const user = useUser();

  const {data} = api.posts.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-x md:max-w-2xl">
        <div>
          {!user.isSignedIn && <SignInButton/>}
          {!!user.isSignedIn && <SignOutButton/>}
        </div>
        <div>
          {data?.map((post) => ( <div key={post.id} >{post.content}</div>))}
        </div>
        </div>
      <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
