import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const CreatePostWizard = () => {

  const {user }= useUser();

  if(!user) return null;

  return (
    <div>
       <img src={user.profileImageUrl} alt="profile-img" className="h-14  w-14 rounded-full" />
    </div>
  );
};

const Home: NextPage = () => {

  const user = useUser();

  console.log(user);

  const {data} = api.posts.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-x md:max-w-2xl">
        <div>
          {!user.isSignedIn && <SignInButton/>}
          {user.isSignedIn && <CreatePostWizard/>}
        </div>
        <div>
          {data?.map(({ post, author }) => ( 
          <div key={post.id} >
            {post.content}
            </div>
            ))}
        </div>
        </div>
      <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
